#!/bin/bash

echo 'Building libraries...'
sudo make install -I parcel/udt/src/
make
echo 'Installing libraries to /usr/local/lib'
sudo make install
echo 'Installing python package'
sudo $(which python) setup.py install
