#!/bin/bash

echo 'Building libraries...'
cd parcel/udt
sudo make
cd ../src
sudo make
sudo make install
python setup.py
echo 'Installing libraries to /usr/local/lib'
sudo make install
echo 'Installing python package'
sudo $(which python) setup.py install
